export const POKEMONS_ACTION_TYPES = {
  SET_POKEMONS: "pokemons/SET_POKEMONS",
  FETCH_POKEMONS_START: "pokemons/FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "pokemons/FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_FAILED: "pokemons/FETCH_POKEMONS_FAILED",
};
